apiVersion: v1
kind: Namespace
metadata:
  name: sseservertest
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sseservertest
  labels:
    app: sseservertest
spec:
  selector:
    matchLabels:
      app: sseservertest
  template:
    metadata:
      labels:
        app: sseservertest
    spec:
      containers:
        - name: sseservertest
          image: tnotheis/sseserver-test
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: sseservertest
  labels:
    app: sseservertest
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: sseservertest
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: sseservertest
spec:
  # hostnames: # Probably optional
  # - <hostname> # Probably optional
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: <gateway-name> # TODO: Replace with your gateway name
  rules:
    - backendRefs:
        - kind: Service
          name: sseservertest
          port: 8080
      matches:
        - path:
            type: PathPrefix
            value: /sse
---
apiVersion: alb.networking.azure.io/v1
kind: RoutePolicy
metadata:
  name: sseservertest
spec:
  targetRef:
    kind: HTTPRoute
    name: sseservertest
    group: gateway.networking.k8s.io
  default:
    timeouts:
      routeTimeout: 0s
